name: OutPuts Demo
on: push
jobs:
  build:
    outputs:
      version: ${{ steps.Id1.outputs.version }}
    runs-on: ububuntu-latest
    steps:
      - name: Build Step
        id: Id1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
       
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying the app with version ${{ needs.build.outputs.version }}"
    
